hms/Areas/Setup/Controllers/ParentMenuController.cs
using hms.DataAccess.Repository.IRepository;
using hms.DataModel;
using hms.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace hms.Areas.Setup.Controllers
{
    [Area("Setup")]
    [hmsAuthorization(controller_id = 8)]
    public class ParentMenuController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ParentMenuController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult ManageParentMenu(int? id)
        {
            US_PARENT_MENU _obj = new US_PARENT_MENU();
            if (id != null)
            {
                _obj = _unitOfWork.US_PARENT_MENU.Get(id.Value);
                if (_obj == null)
                {
                    TempData["msg"] = SweetMsg.SaveWarningOK();
                }
            }
            return View(_obj);
        }
        [HttpPost]
        public IActionResult ManageParentMenu(US_PARENT_MENU _obj)
        {
            if (ModelState.IsValid)
            {
                if (_obj.ID == 0)
                {
                    _obj.ID = _unitOfWork.US_PARENT_MENU.GetAll().Max(x => x.ID) + 1;
                    _obj.IS_ACTIVE = true;
                    _unitOfWork.US_PARENT_MENU.Add(_obj);
                }
                else
                {
                    _unitOfWork.US_PARENT_MENU.Update(_obj);
                }
                _unitOfWork.Save();
                TempData["msg"] = SweetMsg.SaveSuccess();
                return RedirectToAction(nameof(ManageParentMenu));
            }
            TempData["msg"] = SweetMsg.SaveErrorOK();
            _obj.ID = 0;
            return View(_obj);
        }
        public IActionResult GetAll()
        {
            var obj = _unitOfWork.US_PARENT_MENU.GetAll();
            return Json(new { data = obj });
        }

        //[AcceptVerbs("PUT")]
        public IActionResult Remove(int id)
        {
            bool result = _unitOfWork.US_PARENT_MENU.Delete(id);
            if (result)
            {
                _unitOfWork.Save();
                return Json(new { success = true, messages = SweetMsg._DeleteSuccess });
            }
            return Json(new { success = false, messages = SweetMsg._DeleteError });
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyParentMenuName(string PARENT_NAME, int ID)
        {
            if (ID != 0)
            {
                var obj = _unitOfWork.US_PARENT_MENU.Get(ID);
                if (obj.IS_ACTIVE == false && obj.PARENT_NAME == PARENT_NAME)
                {
                    return Json(true);
                }
            }
            bool result = _unitOfWork.US_PARENT_MENU.GetAll(x => x.PARENT_NAME == PARENT_NAME).Any();
            return Json(!result);
        }
    }
}

hms/Areas/Setup/Views/ParentMenu/ManageParentMenu.cshtml
@model hms.DataModel.US_PARENT_MENU

@{
    ViewData["Title"] = "Parent Menu";
}

<div class="card card-secondary card-outline">

    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-edit"></i>
            @ViewData["Title"]
        </h3>
    </div>

    <form asp-action="ManageParentMenu" asp-controller="ParentMenu" method="post">

        <div class="card-body">
            <div class="col-md-12">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <input hidden asp-for="ID" />
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="PARENT_NAME" class="control-label"></label>
                            <input asp-for="PARENT_NAME" class="form-control form-control-sm" />
                            <span asp-validation-for="PARENT_NAME" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="PARENT_BN_NAME" class="control-label"></label>
                            <input asp-for="PARENT_BN_NAME" class="form-control form-control-sm" />
                            <span asp-validation-for="PARENT_BN_NAME" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="PARENT_ICON" class="control-label"></label>
                            <input asp-for="PARENT_ICON" class="form-control form-control-sm" />
                            <span asp-validation-for="PARENT_ICON" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="IS_ACTIVE" class="control-label"></label>
                            <div class="form-check">
                                <input class="form-check-input" asp-for="IS_ACTIVE" />
                                <label class="form-check-label"> @Html.DisplayNameFor(model => model.IS_ACTIVE)</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary float-right">Submit</button>
            <input type="button" onclick="location.reload();" class="btn btn-secondary float-left" value="Cancel" />
        </div>

    </form>
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">@ViewData["Title"] List</h3>
    </div>
    <div class="card-body table-responsive">
        <table id="myTable1" class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Bangla Name</th>
                    <th>Icon</th>
                    <th>Status</th>
                    <th>Option</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Areas/Setup/parentmenu.js"></script>
}