hms/Areas/Setup/Controllers/ChildMenuController.cs
using hms.DataAccess.Repository.IRepository;
using hms.DataModel;
using hms.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace hms.Areas.Setup.Controllers
{
    [Area("Setup")]
    [hmsAuthorization(controller_id = 6)]
    public class ChildMenuController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ChildMenuController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult ManageChildMenu(int? id)
        {
            DropDownFor_ManageChildMenu();
            US_CHILD_MENU _obj = new US_CHILD_MENU();
            if (id != null)
            {
                _obj = _unitOfWork.US_CHILD_MENU.Get(id.Value);
                if (_obj == null)
                {
                    TempData["msg"] = SweetMsg.SaveWarningOK();
                }
            }
            return View(_obj);
        }
        [HttpPost]
        public IActionResult ManageChildMenu(US_CHILD_MENU _obj)
        {
            if (ModelState.IsValid)
            {
                if (_obj.ID == 0)
                {
                    _obj.ID = _unitOfWork.US_CHILD_MENU.GetAll().Max(x => x.ID) + 1;
                    _obj.IS_ACTIVE = true;
                    _unitOfWork.US_CHILD_MENU.Add(_obj);
                }
                else
                {
                    _unitOfWork.US_CHILD_MENU.Update(_obj);
                }
                _unitOfWork.Save();
                TempData["msg"] = SweetMsg.SaveSuccess();
                return RedirectToAction(nameof(ManageChildMenu));
            }
            TempData["msg"] = SweetMsg.SaveErrorOK();
            DropDownFor_ManageChildMenu();
            _obj.ID = 0;
            return View(_obj);
        }

        private void DropDownFor_ManageChildMenu()
        {
            ViewBag.US_MODULE_ID = _unitOfWork.US_MODULE.GetAll().Select(i => new SelectListItem { Value = i.ID.ToString(), Text = i.MODULE_NAME });
            ViewBag.US_PARENT_MENU_ID = _unitOfWork.US_PARENT_MENU.GetAll().Select(i => new SelectListItem { Value = i.ID.ToString(), Text = i.PARENT_NAME });
        }
        public IActionResult GetAll()
        {
            var obj = _unitOfWork.US_CHILD_MENU.GetAll(includeProperties: "US_MODULE,US_PARENT_MENU");
            return Json(new { data = obj });
        }

        //[AcceptVerbs("PUT")]
        public IActionResult Remove(int id)
        {
            bool result = _unitOfWork.US_CHILD_MENU.Delete(id);
            if (result)
            {
                _unitOfWork.Save();
                return Json(new { success = true, messages = SweetMsg._DeleteSuccess });
            }
            return Json(new { success = false, messages = SweetMsg._DeleteError });
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult VerifyChildMenuName(string CHILD_NAME, int ID)
        {
            if (ID != 0)
            {
                var obj = _unitOfWork.US_CHILD_MENU.Get(ID);
                if (obj.IS_ACTIVE == false && obj.CHILD_NAME == CHILD_NAME)
                {
                    return Json(true);
                }
            }
            bool result = _unitOfWork.US_CHILD_MENU.GetAll(x => x.CHILD_NAME == CHILD_NAME).Any();
            return Json(!result);
        }
    }
}

hms/Areas/Setup/Views/ChildMenu/ManageChildMenu.cshtml
@model hms.DataModel.US_CHILD_MENU

@{
    ViewData["Title"] = "Child Menu";
}

<div class="card card-secondary card-outline">

    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-edit"></i>
            @ViewData["Title"]
        </h3>
    </div>

    <form asp-action="ManageChildMenu" asp-controller="ChildMenu" method="post">
        <div class="card-body">
            <div class="col-md-12">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row">
                    <input hidden asp-for="ID" />
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="CHILD_NAME" class="control-label"></label>
                            <input asp-for="CHILD_NAME" class="form-control form-control-sm" />
                            <span asp-validation-for="CHILD_NAME" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="CHILD_BN_NAME" class="control-label"></label>
                            <input asp-for="CHILD_BN_NAME" class="form-control form-control-sm" />
                            <span asp-validation-for="CHILD_BN_NAME" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="CHILD_ICON" class="control-label"></label>
                            <input asp-for="CHILD_ICON" class="form-control form-control-sm" />
                            <span asp-validation-for="CHILD_ICON" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="AREA_NAME" class="control-label"></label>
                            <input asp-for="AREA_NAME" class="form-control form-control-sm" />
                            <span asp-validation-for="AREA_NAME" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="CONTROLLER_NAME" class="control-label"></label>
                            <input asp-for="CONTROLLER_NAME" class="form-control form-control-sm" />
                            <span asp-validation-for="CONTROLLER_NAME" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="ACTION_NAME" class="control-label"></label>
                            <input asp-for="ACTION_NAME" class="form-control form-control-sm" />
                            <span asp-validation-for="ACTION_NAME" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="MODULE_ID" class="control-label"></label>
                            <select asp-for="MODULE_ID" class="form-control form-control-sm" asp-items="ViewBag.MODULE_ID"><option selected>-Select-</option></select>
                            <span asp-validation-for="MODULE_ID" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="PARENT_MENU_ID" class="control-label"></label>
                            <select asp-for="PARENT_MENU_ID" class="form-control form-control-sm" asp-items="ViewBag.PARENT_MENU_ID"><option selected>-Select-</option></select>
                            <span asp-validation-for="PARENT_MENU_ID" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label asp-for="IS_ACTIVE" class="control-label"></label>
                            <div class="form-check">
                                <input class="form-check-input" asp-for="IS_ACTIVE" />
                                <label class="form-check-label"> @Html.DisplayNameFor(model => model.IS_ACTIVE)</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary float-right">Submit</button>
            <input type="button" onclick="location.reload();" class="btn btn-secondary float-left" value="Cancel" />
        </div>

    </form>

</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">@ViewData["Title"] List</h3>
    </div>
    <div class="card-body table-responsive">
        <table id="myTable1" class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Bangla Name</th>
                    <th>Icon</th>
                    <th>Area</th>
                    <th>Controller</th>
                    <th>Action</th>
                    <th>Module</th>
                    <th>Parent Menu</th>
                    <th>Status</th>
                    <th>Option</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Areas/Setup/childmenu.js"></script>
}